server:
  port: 10000
  servlet:
    context-path: /api

  error:
    include-stacktrace: never
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./h2/tbl_user;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mmusic:
  app:
    jwtCookieName: mmusic-api
    jwtSecret: d7116d00-7347-11ed-a1eb-0242ac120002
    jwtExpirationMs: 86400000